services:
  rpc:
    container_name: lumia-${NETWORK_ENV}-rpc
    image: hermeznetwork/cdk-erigon:v2.60.2
    user: root
    restart: always
    environment:
      - CDK_ERIGON_SEQUENCER=0
    command: ["--config", "/root/dynamic-configs/dynamic-lumia-testnet-config.yaml"]
    volumes:
      - ./config/${NETWORK_ENV:-testnet}/dynamic-lumia-testnet-config.yaml:/root/dynamic-configs/dynamic-lumia-testnet-config.yaml:ro
      - ./config/${NETWORK_ENV:-testnet}/dynamic-lumia-testnet-allocs.json:/root/dynamic-configs/dynamic-lumia-testnet-allocs.json
      - ./config/${NETWORK_ENV:-testnet}/dynamic-lumia-testnet-chainspec.json:/root/dynamic-configs/dynamic-lumia-testnet-chainspec.json
      - ./config/${NETWORK_ENV:-testnet}/dynamic-lumia-testnet-conf.json:/root/dynamic-configs/dynamic-lumia-testnet-conf.json
      - ./data/${NETWORK_ENV:-testnet}/rpc/:/data
    ports:
      - 8545:8545 # rpc
      - 8546:8546 # ws
      - 9000:9000 # datastream
      - 9090:9090 # metrics
