services:
  rpc:
    container_name: rpc
    image: hermeznetwork/cdk-erigon:v2.61.22
    user: root
    restart: always
    env_file:
      .env
    environment:
      - CDK_ERIGON_SEQUENCER=0
      - NETWORK_ENV=${NETWORK_ENV:-testnet}
      - CHAIN_NAME=${CHAIN_NAME:-dynamic-lumia-testnet}
    command: 
      - "--config" 
      - "/root/dynamic-configs/${CHAIN_NAME:-dynamic-lumia-testnet}-config.yaml"
      - "--zkevm.l2-sequencer-rpc-url"
      - ${CDK_ERIGON_ZKEVM_L2_SEQUENCER_RPC_URL}
      - "--zkevm.l2-datastreamer-url"
      - ${CDK_ERIGON_L2_DATASTREAMER_URL}
      - "--zkevm.l1-rpc-url"
      - ${CDK_ERIGON_L1_RPC_URL}
    volumes:
      - ./config/${NETWORK_ENV:-testnet}/dynamic-${NETWORK_ENV:-testnet}-config.yaml:/root/dynamic-configs/${CHAIN_NAME:-dynamic-lumia-testnet}-config.yaml:ro
      - ./config/${NETWORK_ENV:-testnet}/dynamic-${NETWORK_ENV:-testnet}-allocs.json:/root/dynamic-configs/${CHAIN_NAME:-dynamic-lumia-testnet}-allocs.json
      - ./config/${NETWORK_ENV:-testnet}/dynamic-${NETWORK_ENV:-testnet}-chainspec.json:/root/dynamic-configs/${CHAIN_NAME:-dynamic-lumia-testnet}-chainspec.json
      - ./config/${NETWORK_ENV:-testnet}/dynamic-${NETWORK_ENV:-testnet}-conf.json:/root/dynamic-configs/${CHAIN_NAME:-dynamic-lumia-testnet}-conf.json
      - ./data/${NETWORK_ENV:-testnet}:/data
    ports:
      - 8545:8545 # rpc
      - 8546:8546 # ws
      - 9000:9000 # datastreamer
      - 9090:9090 # metrics
