
IsTrustedSequencer = false

[Log]
Environment = "production" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[State]
[State.DB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "cdk-validium-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200
[State.Batch]
[State.Batch.Constraints]
MaxTxsPerBatch = 300
MaxBatchBytesSize = 120000
MaxCumulativeGasUsed = 1125899906842624
MaxKeccakHashes = 2145
MaxPoseidonHashes = 252357
MaxPoseidonPaddings = 135191
MaxMemAligns = 236585
MaxArithmetics = 236585
MaxBinaries = 473170
MaxSteps = 7570538
MaxSHA256Hashes = 1596

[Pool]
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize = 100132
MaxTxDataBytesSize = 100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
[Pool.EffectiveGasPrice]
Enabled = false
L1GasPriceFactor = 0.25
ByteGasCost = 16
ZeroByteGasCost = 4
NetProfit = 1
BreakEvenFactor = 1.1
FinalDeviationPct = 10
EthTransferGasPrice = 0
EthTransferL1GasPriceFactor = 0
L2GasPriceSuggesterFactor = 0.5
[Pool.DB]
User = "pool_user"
Password = "pool_password"
Name = "pool_db"
Host = "cdk-validium-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Etherman]
URL = ""
ForkIDChunkSize = 10000
MultiGasProvider = false
[Etherman.Etherscan]
ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = true
[RPC.WebSockets]
Enabled = true
Port = 8546

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 50
TrustedSequencerURL = ""       # If it is empty or not specified, then the value is read from the smc
SyncBlockProtection = "latest" # latest, finalized, safe
L1SyncCheckL2BlockHash = false
ExecuteBatchNoCountersFlag = true
[Synchronizer.L2Synchronization]
CheckLastL2BlockHashOnCloseBatch = false

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h"
TxLifetimeCheckInterval = "10m"
TxLifetimeMax = "3h"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"
[Sequencer.Finalizer]
NewTxsWaitInterval = "100ms"
ForcedBatchesTimeout = "60s"
ForcedBatchesCheckInterval = "10s"
ForcedBatchesL1BlockConfirmations = 64
L1InfoTreeL1BlockConfirmations = 64
L1InfoTreeCheckInterval = "10s"
BatchMaxDeltaTimestamp = "120s"
L2BlockMaxDeltaTimestamp = "3s"
ResourceExhaustedMarginPct = 10
HaltOnBatchNumber = 0
SequentialBatchSanityCheck = false
SequentialProcessL2Block = true
[Sequencer.Finalizer.Metrics]
Interval = "60m"
EnableLog = true
[Sequencer.StreamServer]
Port = 0
Filename = ""
Enabled = false

[L2GasPriceSuggester]
Type = "default"
DefaultGasPriceWei = 1000000000
MaxGasPriceWei = 0

[MTClient]
URI = "cdk-validium-executor:5062"

[Executor]
URI = "cdk-validium-executor:5071"
MaxResourceExhaustedAttempts = 3
WaitOnResourceExhaustion = "1s"
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = false

[HashDB]
User = "prover_user"
Password = "prover_pass"
Name = "prover_db"
Host = "cdk-validium-prover-db"
Port = "5432"
EnableLog = false
MaxConns = 200
